[mcp_servers.better-auth]
url = "https://mcp.inkeep.com/better-auth/mcp"

[mcp_servers.better-t-stack]
command = "pnpm"
args = [
    "dlx",
    "create-better-t-stack@latest",
    "mcp",
]

[mcp_servers.context7]
command = "npx"
args = [
    "-y",
    "@upstash/context7-mcp",
]

[mcp_servers.neon]
url = "https://mcp.neon.tech/mcp"

[mcp_servers.svelte]
url = "https://mcp.svelte.dev/mcp"
