packages:
  - apps/*
  - packages/*
allowBuilds:
  esbuild: true
  sharp: true
catalog:
  dotenv: ^17.4.2
  zod: ^4.4.3
  typescript: ^6
  "@types/node": ^22.13.14
  "@orpc/server": ^1.14.6
  "@orpc/client": ^1.14.6
  "@orpc/openapi": ^1.14.6
  "@orpc/zod": ^1.14.6
  better-auth: 1.6.23
